(()=>{'use strict';
const API='https://txjuiaiwffsxfcrxpkvd.supabase.co/functions/v1/line-service-hub-web';
const KEY='linehub.cloudStaffToken';
const $=id=>document.getElementById(id);
async function call(body){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),cache:'no-store'});const d=await r.json().catch(()=>({success:false,error:'ระบบตอบกลับไม่ถูกต้อง'}));if(!r.ok||d.success===false)throw new Error(d.error||'ไม่สามารถเชื่อมต่อระบบได้');return d}
function session(){return sessionStorage.getItem(KEY)||''}
function clear(){sessionStorage.removeItem(KEY);$('appCard').classList.add('hidden');$('loginCard').classList.remove('hidden');$('password').value=''}
function row(item){const wrap=document.createElement('article');wrap.className='request';const info=document.createElement('div');const name=document.createElement('strong');name.textContent=item.masked_name||'สมาชิกครอบครัว';const meta=document.createElement('p');meta.textContent=item.requested_at?'ขอเมื่อ '+new Date(item.requested_at).toLocaleString('th-TH'):'รอตรวจสอบ';info.append(name,meta);const acts=document.createElement('div');acts.className='actions';for(const [label,approve,cls] of [['อนุมัติ',true,''],['ปฏิเสธ',false,'secondary']]){const b=document.createElement('button');b.type='button';b.textContent=label;b.className=cls;b.onclick=async()=>{if(!confirm((approve?'อนุมัติ':'ปฏิเสธ')+'คำขอนี้?'))return;b.disabled=true;$('appMsg').textContent='กำลังบันทึก...';try{await call({action:'family-decide',token:session(),line_user_hash:item.line_user_hash,member_patient_ref:item.member_patient_ref,approve});$('appMsg').textContent=approve?'อนุมัติแล้ว และ Cloud แจ้งผู้ใช้ทาง LINE':'ปฏิเสธคำขอแล้ว';await load()}catch(e){$('appMsg').textContent=e.message}finally{b.disabled=false}};acts.append(b)}wrap.append(info,acts);return wrap}
async function load(){const token=session();if(!token)return clear();$('appMsg').textContent='';$('list').replaceChildren();try{const snap=await call({action:'snapshot',token});$('who').textContent=(snap.profile?.displayName||snap.profile?.adminId||'เจ้าหน้าที่')+' · '+(snap.profile?.role||'');const r=await call({action:'family-pending',token});const items=r.items||[];if(!items.length){const e=document.createElement('div');e.className='empty';e.textContent='ไม่มีคำขอรออนุมัติ';$('list').append(e)}else items.forEach(x=>$('list').append(row(x)));$('loginCard').classList.add('hidden');$('appCard').classList.remove('hidden')}catch(e){$('appMsg').textContent=e.message;if(/เซสชัน/.test(e.message))clear()}}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginMsg').textContent='';const b=e.submitter;b.disabled=true;try{const r=await call({action:'login',username:$('username').value,password:$('password').value});sessionStorage.setItem(KEY,r.token);$('password').value='';await load()}catch(err){$('loginMsg').textContent=err.message}finally{b.disabled=false}};
$('refreshBtn').onclick=load;$('logoutBtn').onclick=clear;load();
})();